### ISSUE TITLE
Completely breaks Nova 4.0

### ISSUE THREAD

**Issue by ryanrapini** [Bhavin9898/Nova-Month-Picker-Field#1]
Hey! Thanks for contributing this plugin, looks like exactly what I need. Unfortunately I can't get it to work.

Tried to install this plugin but it completely breaks my Nova install (blank screen when viewing Nova, even when not using any new code, only after running `composer install`

```
month-picker:1 Uncaught TypeError: window.Vue.use is not a function
    at Object.<anonymous> (month-picker:1:12284)
    at n (month-picker:1:110)
    at Object.<anonymous> (month-picker:1:11974)
    at n (month-picker:1:110)
    at month-picker:1:11182
    at app.js:106:47
    at Array.forEach (<anonymous>)
    at mo.boot (app.js:106:27)
    at mo.liftOff (app.js:162:10)
    at main:52:14
```

![image](https://github.com/Bhavin9898/Nova-Month-Picker-Field/assets/286087/d5365ee7-8f5f-422a-9009-6e4b62d7ea48)

```
Nova "~4.0",
Laravel "^10.0",
PHP "^8.0.2",
```

Let me know if you need additional info

**Comment by Ivankali2020** [comment]
same here can you do for v 4.0

**Comment by btrsco** [comment]
Abandoned? its been a year 😆

**Comment by bhavinzwt** [comment]
we will work on it and fix it ASAP.
